---
- name: Install samba smb-client
  hosts: samba_server
  become: yes

  tasks:
  - name: Install samba
    apt: name=samba state=latest update_cache=yes

  - name: Start and enable samba
    ansible.builtin.systemd: name=samba.service state=started enabled=yes
