---
- name: Install samba smb-client
  hosts: samba_server
  become: yes

  tasks:
  - name: Install samba
    apt: name=samba state=latest update_cache=yes

  - name: Start and enable samba
    ansible.builtin.systemd: name=smbd state=started enabled=yes
  - name: Config samba_server
    vars:
      var_workgroup: 'WORKGROUP'
      var_allow_guests: 'no'
    ansible.builtin.template:
      src: templates/smb.conf.j2
      dest: /etc/samba.smb.conf
      owner: root
      group: root
      mode: '0644'
      backup: yes

  handlers:
  - name: Restart samba server
    ansible.builtin.systemd: name=smbd state=restarted enabled=yes
