---
- name: Install samba smb-client
  hosts: samba_server
  become: yes

  tasks:
  - name: Config samba share
    vars:
      var_workgroup: 'WORKGROUP'
      var_allow_guests: 'no'
    ansible.builtin.template:
      src: templates/smb_share_block.j2
      dest: /etc/samba/smb.conf
      owner: root
      group: root
      mode: '0644'
      backup: yes
